CREATE TABLE IF NOT EXISTS "ppwp_tps" (
	"kode" text PRIMARY KEY NOT NULL,
	"provinsi" text NOT NULL,
	"kabupaten_kota" text NOT NULL,
	"kecamatan" text NOT NULL,
	"kelurahan_desa" text NOT NULL,
	"tps" text NOT NULL,
	"suara_paslon_1" integer NOT NULL,
	"suara_paslon_2" integer NOT NULL,
	"suara_paslon_3" integer NOT NULL,
	"hasil_1" text,
	"hasil_2" text,
	"hasil_3" text,
	"suara_sah" integer,
	"suara_total" integer,
	"pemilih_dpt_j" integer,
	"pemilih_dpt_l" integer,
	"pemilih_dpt_p" integer,
	"pengguna_dpt_j" integer,
	"pengguna_dpt_l" integer,
	"pengguna_dpt_p" integer,
	"pengguna_dptb_j" integer,
	"pengguna_dptb_l" integer,
	"pengguna_dptb_p" integer,
	"suara_tidak_sah" integer,
	"pengguna_total_j" integer,
	"pengguna_total_l" integer,
	"pengguna_total_p" integer,
	"pengguna_non_dpt_j" integer,
	"pengguna_non_dpt_l" integer,
	"pengguna_non_dpt_p" integer,
	"psu" text,
	"ts" text,
	"status_suara" boolean,
	"status_adm" boolean,
	"updated_at" timestamp DEFAULT now(),
	"created_at" timestamp DEFAULT now()
);
