CREATE TABLE IF NOT EXISTS "pdpr_tps" (
	"kode" text PRIMARY KEY NOT NULL,
	"provinsi_kode" text NOT NULL,
	"provinsi_nama" text,
	"kabupaten_kota_kode" text NOT NULL,
	"kabupaten_kota_nama" text,
	"kecamatan_kode" text NOT NULL,
	"kecamatan_nama" text,
	"kelurahan_desa_kode" text NOT NULL,
	"kelurahan_desa_nama" text,
	"tps" text NOT NULL,
	"suara_partai_1" integer,
	"suara_partai_2" integer,
	"suara_partai_3" integer,
	"suara_partai_4" integer,
	"suara_partai_5" integer,
	"suara_partai_6" integer,
	"suara_partai_7" integer,
	"suara_partai_8" integer,
	"suara_partai_9" integer,
	"suara_partai_10" integer,
	"suara_partai_11" integer,
	"suara_partai_12" integer,
	"suara_partai_13" integer,
	"suara_partai_14" integer,
	"suara_partai_15" integer,
	"suara_partai_16" integer,
	"suara_partai_17" integer,
	"suara_partai_18" integer,
	"suara_partai_19" integer,
	"suara_partai_20" integer,
	"suara_partai_21" integer,
	"suara_partai_22" integer,
	"suara_partai_23" integer,
	"suara_partai_24" integer,
	"images" json,
	"suara_sah" integer,
	"suara_total" integer,
	"pemilih_dpt_j" integer,
	"pemilih_dpt_l" integer,
	"pemilih_dpt_p" integer,
	"pengguna_dpt_j" integer,
	"pengguna_dpt_l" integer,
	"pengguna_dpt_p" integer,
	"pengguna_dptb_j" integer,
	"pengguna_dptb_l" integer,
	"pengguna_dptb_p" integer,
	"suara_tidak_sah" integer,
	"pengguna_total_j" integer,
	"pengguna_total_l" integer,
	"pengguna_total_p" integer,
	"pengguna_non_dpt_j" integer,
	"pengguna_non_dpt_l" integer,
	"pengguna_non_dpt_p" integer,
	"psu" text,
	"ts" text,
	"status_suara" boolean,
	"status_adm" boolean,
	"url_page" text,
	"url_api" text,
	"updated_at" timestamp DEFAULT now(),
	"created_at" timestamp DEFAULT now(),
	"fetch_count" integer DEFAULT 0
);
